### ISSUE TITLE
[Feature]: kubectl user can build images by creating a BuildWorkload resource

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1002]
### Background

**As an** engineer seeking to implement an alternative build flow implementation for korifi
**I want** to have a default implementation of the BuildWorkload reconciler that replicates the current korifi build process
**So that** I have an example to work from and a clearly defined API (via the resource spec and status)

### Acceptance Criteria

**GIVEN** that I have a running instance of korifi (setup via our install scripts on kind, GKE, etc)
**WHEN** I create a BuildWorkload resource for an image ref that contains my application source
**THEN** I should see that the BuildWorkload's status is updated to reflect that it is running
**AND** I should eventually see that the BuildWorkload's status shows that it finished building successfully
**AND** the BuildWorkload's status should contain a reference to the built image

---

**GIVEN** that I have a running instance of korifi (setup via our install scripts on kind, GKE, etc)
**WHEN** I create a BuildWorkload resource for an image ref that contains application source that will fail to build (e.g. due to compilation errors)
**THEN** I should see that the BuildWorkload's status is updated to reflect that it is running
**AND** I should eventually see that the BuildWorkload's status shows that it is no longer running and that it errored

### Dev Notes
- This story needs to create the CRD for BuildWorkload

Here is a draft example CR for the BuildWorkload resource:

```yaml
apiVersion: ext.cloudfoundry.org/v1alpha1 # this apiGroup is a first draft
kind: BuildWorkload
metadata:
  name: my-app-guid
  namespace: my-space-guid
spec:
  buildRef:
    name: my-build-guid
  env:
    - name: VCAP_SERVICES
      valueFrom:
        secretKeyRef:
          key: VCAP_SERVICES
          name: vcap-services-secret
  source:
    registry:
      image: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages/eb60d1d0-5de1-4051-ac05-a4047f2b191a@sha256:987d6b085314a16ba5566fd0821d5a2f59e1a54ea11b8c0e2cd09309482d0481
      imagePullSecrets:
        - name: image-registry-credentials
status:
  conditions:
  - status: 'False'
    type: Running
  - status: 'True'
    type: Succeeded
  droplet: # We may want to rename this to be less CF-specific, or perhaps remove it and move the subkeys up
    ports: []
    processTypes:
      - command: node /workspace/server.js
        type: web
    registry:
      image: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images/dbcee519-d239-4272-a264-3c1ce36a3e0a@sha256:6cee35c7d3ddc688bc45745e7c54432063221f71c6a092a649dcdff17a028c90
      imagePullSecrets:
        - name: image-registry-credentials
    stack: io.buildpacks.stacks.bionic
```

- For this story, create a top-level directory inside of the `korifi` repo that contains a self-contained kubebuilder project (e.g. `kpack-image-builder`)
- The install scripts need to deploy this new codebase to the k8s cluster with a sane default configuration
- Eventually there will be a single BuildWorkload for each App, and we will prevent multiple concurrent builds. This is why the AC delve into the case when the Workload is updated.
- This new subproject should be independent from the existing deployments, so ensure it has independent RBAC, etc.
