### ISSUE TITLE
[Feature]: Developer cannot create a task without a command

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1020]
### Background

**As a** developer
**I want** to run tasks
**So that** I can execute one-off workloads

### Acceptance Criteria

**GIVEN** `app1` exists in `org1` and `space1`
- **WHEN I** create the following resource:
  ```yaml
  ---
  apiVersion: workloads.cloudfoundry.org/v1alpha1
  kind: Task
  metadata:
    name: <the-task-guid>
    namespace: <space1-guid>
  spec:
    name: my-task
    appRef:
      name: app1
  ```
  **THEN I** see a error complaining about the lack of `command`
- **WHEN I** make the following request to our shim API:
  ```
  POST /v3/apps/<app1-guid>/tasks HTTP/1.1
  Authorization: ...
  Content-type: application/json
  ```
  ```json
  {}
  ```
  **THEN I** get the following response:
  ```
  HTTP/1.1 422 Unprocessable Entity
  Content-type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10008,
        "detail": "No command provided",
        "title": "CF-UnprocessableEntity"
      }
    ]
  }
  ```
