### ISSUE TITLE
[Feature]: Developer can see the status of a task via the Kubernetes API

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1031]
### Background

**As a** developer
**I want** to run tasks
**So that** I can execute one-off workloads

### Acceptance Criteria

**GIVEN** I have [created a task](https://github.com/cloudfoundry/korifi/issues/1016)
**AND** the task hasn't started its execution yet
**WHEN I** look at the task as a Kubernetes resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Created”
```

**GIVEN** I have created a task
**AND** the task has started its execution but not completed it yet
**WHEN I** look at the task as a Kubernetes resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Created”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
```

**GIVEN** I have created a task
**AND** the task has completed successfully
**WHEN I** look at the task as a Kubernetes resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Created”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Succeeded”
```

**GIVEN** I have created a task
**AND** the task has failed
**WHEN I** look at the task as a Kubernetes resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Created”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Failed”
```
