### ISSUE TITLE
[Feature]: kubectl user can see accurate BuildReconcilerInfo resource for the default build reconciler

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1054]
### Blockers/Dependencies

[#1002]

### Background

**As a** kubectl user
**I want** to see a `BuildReconcilerInfo` resource for the default build reconciler (draft name `kpack-image-builder`), which includes its supported buildpacks
**So that** I know which buildpacks can be passed to BuildWorkload resources on the cluster 

### Acceptance Criteria

**GIVEN** a deployment of korifi which uses the default BuildWorkload reconciler (draft name `kpack-image-builder`)
**WHEN I** run `kubectl get BuildReconcilerInfo -n cf`
**THEN I** should see a single item
**AND** that single item should contain a complete list of the paketo buildpacks supported by the reconciler

---

**WHEN I**  change the kpack ClusterBuilder I'm using in my configuration to be a ClusterBuilder with a different list of buildpacks in a different order
**THEN I** should see that the `BuildReconcilerInfo` resource reflects the new configuration (including its position within the list)

### Dev Notes
This feature introduces the `BuildReconcilerInfo` resource to `korifi.cloudfoundry.org`.

Here's a draft version of the CR:
```yaml
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: BuildReconcilerInfo
metadata:
  name: kpack-image-builder
  namespace: cf
spec: {}
status:
  buildpacks:
  - name: paketo-buildpacks/java
    stack: io.buildpacks.stacks.bionic
    version: 0.42
    updatedAt: # time of last change to the buildpack
    createdAt: # time the buildpack was first added to the list (since creation time probably isn't actually available through kpack)
  - name: paketo-buildpacks/go
  # ...
```

* the record should be created/updated in the root namespace (i.e. `cf`)
* the `kpack-image-builder` reconciler should only create/update the one `BuildReconcilerCapabilities` record with the name it uses, and ignore any others that may already exist or be created later.

* As of 2022/05/06, the list of supported buildpacks is:
  - `paketo-buildpacks/java`
  - `paketo-buildpacks/go`
  - `paketo-buildpacks/nodejs`
  - `paketo-buildpacks/ruby`
  - `paketo-buildpacks/procfile`
