### ISSUE TITLE
[Feature]: Developer cannot create a task without an app

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1082]
### Background

**As a** developer
**I want** to run tasks
**So that** I can execute one-off workloads

### Acceptance Criteria

**GIVEN** `space1` exists in `org1`
- **WHEN I** create the following resource:
  ```yaml
  ---
  apiVersion: workloads.cloudfoundry.org/v1alpha1
  kind: Task
  metadata:
    name: <the-task-guid>
    namespace: <space1-guid>
  spec:
    name: my-task
    command: ["echo", "hello"]
  ```
  **THEN I** see a error complaining about the lack of `appRef`
  **AND I** see the resource has *not* been created
- **WHEN I** create the following resource:
  ```yaml
  ---
  apiVersion: workloads.cloudfoundry.org/v1alpha1
  kind: Task
  metadata:
    name: <the-task-guid>
    namespace: <space1-guid>
  spec:
    name: my-task
    command: ["echo", "hello"]
    appRef:
      name: does-not-exist
  ```
  **THEN I** see an error event attached to the task resource, complaining about the fact that the app doesn't exist
