### ISSUE TITLE
[Bug]: CFDomainValidation allows invalid wildcard domains

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/korifi#1100]
### What happened?

CFDomainValidation will allow creation of a CFDomain that is of the form `*.example.com`. This should be considered an invalid domain.

### What you expected to happen

Expected validation to fail and admission to reject creation.

### Acceptance Criteria

GIVEN I have Korifi installed
WHEN I try to create a wildcard domain (e.g.: `*.example.com`)
THEN I get a validation error and the CFDomain is not created

### How to reproduce it (as minimally and precisely as possible)

1. Make a yaml file with the following contents:
```
apiVersion: networking.cloudfoundry.org/v1alpha1
kind: CFDomain
metadata:
  name: foo
  namespace: cf
spec:
  name: *.example.com
```
2. `kubectl apply -f <file>`
3. No validation errors happen

### Environment

Revision of codebase: 9cb53ed53bfb255803d7d1b7d361bb7f353b0885
Kubernetes version (use `kubectl version`): v1.23.1
Cloud provider or hardware configuration: Kind
Others:

### Dev Notes
- Consider using a Kubebuilder regex annotation on the spec field instead of modifying the webhook
