### ISSUE TITLE
[Feature]: kubectl user can see that BuildWorkload.spec.env uses a dedicated Secret for `VCAP_SERVICES`

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1101]
### Blockers/Dependencies

[#1029]

### Background

**As a** kubectl user
**I want** to see that my `VCAP_SERVICES`-encoded service credentials are stored in a secret
**So that** they aren't visible in plain text via kubectl

### Acceptance Criteria

**GIVEN** a working deployment of Korifi
**AND** a CFApp that has a CFServiceBinding to a CFServiceInstance
**WHEN I** use kubectl to describe the CFApp
**THEN I** should see that it has a `status.vcapServicesSecretName` field
**WHEN I** inspect the `Secret` named there in the same namespace
**THEN I** should see that the `Secret` contains only the `VCAP_SERVICES` key, and that its value is correct
**WHEN I** bind a second service to the app
**THEN I** should see that the same `Secret` I inspected before now includes the credential for the service instance I just bound

---

**WHEN I** create a build for that app (e.g. via `cf push`)
**THEN I** should see that the resulting `BuildWorkload` resource has a `spec.env` key that fetches the `VCAP_SERVICES` env var from the same `Secret`

For example:
```yaml
kind: BuildWorkload
metadata:
  name: 51947487-a683-4b04-a717-4e88461e4953
  namespace: cf-space-43626fac-8c65-4955-a7ec-9f753cbe76a0
spec:
  env:
  - name: VCAP_SERVICES
    valueFrom:
      secretKeyRef:
        key: VCAP_SERVICES
        name: my-app-vcap-service-secret
  #...
```

- [x] Make cool diagram
![image](https://user-images.githubusercontent.com/64824162/171736151-1d8cb80a-8355-4425-94ff-6adf64fe0340.png)
- [x] Update CFApp CRD to add status field `vcapServicesSecretName`
- [x] Update CFApp controller to create VCAPServicesSecret and update status field
- [x] Reconcile VCAPServicesSecret body in CFServiceBinding controller
  - [VCAP_SERVICES env var structure](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES)
- [x] Update CFBuildWorkloadController to pull in VCAPServicesSecret and add to Workload spec
- [x] Refactor the builder.go utility to decompose the app env and vcap services env secret generation
- [ ] Update ProcessController to reconcile LRPs appropriately with the changes to builder.go

### Dev Notes

* To avoid code duplication, you should also change the `CFProcessReconciler` to fetch `VCAP_SERVICES` from this same `Secret`, rather than recalculate it. Eventually the `RunWorkload` will exist and be able to pull the env var directly from a `Secret` like `BuildWorkload`, but this smaller change is a step in the right direction.
