### ISSUE TITLE
Support new Kubernetes PodSecurityStandards for workloads

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1220]
As of Kubernetes 1.21 pod security policies are deprecated and are going to be removed in 1.25. They are going to be replaced by the [Pod security admission controller](https://kubernetes.io/docs/concepts/security/pod-security-admission/) and [pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/). This means that pod security is going to be configured per namespace rather than per pod.

We would like to enforce the `restricted` security standard on all workload namespaces

## Accceptance
**Given** a CF space is created
**Then** I see that the corresponding namespace contains the following labels:

```
pod-security.kubernetes.io/audit=restricted
pod-security.kubernetes.io/enforce=restricted
```

**When** I push an application
**Then** The containers of the workload pod has the following security context:

```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

**When** I run a task
**Then** The containers of the job pod has the following security context:

```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

**Discuss on IPM** Do we want to put the `pod-security` labels on the namespaces that back up CFOrgs as well? Technically, korifi does not run pods there, so maybe we don't care? Or maybe we do?

**Note** Depending on when this story is being picked up, the `securityContext` bit might need to be a story in the `eirini-controller` backlog, if eirini-controller is still used to create statefulsets/jobs
