### ISSUE TITLE
[Feature]: `kubectl` user can specify an environment for their `TaskWorkload`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1399]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**WHEN I** [run a `TaskWorkload`](https://github.com/cloudfoundry/korifi/issues/1397) looking like this:
```yaml
---
apiVersion: workloads.cloudfoundry.org/v1alpha1
kind: TaskWorkload
metadata:
  name: my-task
  namespace: my-namespace
spec:
  image: <a-public-container-image>
  command: ["echo", "hello"]
  env:
    - name: MY_ENV_VAR
      value: “foo”
    - name: MY_OTHER_ENV_VAR
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: my-secret-key
```
**THEN I** see the corresponding `Pod`'s `env` is the same to the one I specified

### Dev Notes

We want to support the same `env` configurations as `Pod`s: see [_Environment Variables_](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) for more details.
