### ISSUE TITLE
[Feature]: `kubectl` user can see the status of their `TaskWorkload` execution

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1405]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**GIVEN** I have [created a `TaskWorkload`](https://github.com/cloudfoundry/korifi/issues/1397)
**AND** the command hasn't started running yet
**WHEN I** look at the `TaskWorkload` resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Initialized”
```

**GIVEN** I have created a `TaskWorkload`
**AND** the command has started running but hasn't terminated yet
**WHEN I** look at the `TaskWorkload` resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Initialized”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
```

**GIVEN** I have created a `TaskWorkload`
**AND** the command has terminated successfully
**WHEN I** look at the `TaskWorkload` resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Initialized”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Succeeded”
```

**GIVEN** I have created a `TaskWorkload`
**AND** the command has terminated with a failure
**WHEN I** look at the `TaskWorkload` resource
**THEN I** see something like this in the `conditions` array:
```yaml
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Initialized”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Started”
- lastProbeTime: 2018-01-01T00:00:00Z
  lastTransitionTime: 2018-01-01T00:00:00Z
  status: “True”
  type: “Failed”
```
