### ISSUE TITLE
[Feature]: `kubectl` user can kill a `TaskWorkload` execution by deleting its resource

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1406]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**GIVEN** I have created a `TaskWorkload`
**AND** the command has started running
**WHEN I** delete the `TaskWorkload`
**THEN I** see the associated `Pod` disappear

### Dev Notes

This should only be a matter of setting [owner references](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) properly.

**Comment by kieron-dev** [comment]
This is a no-op. The controller owner reference is already set and checked on the `Job`.

I've manually verified creating a taskworkload with a long sleep successfully creates a pod, and deleting the taskworkload causes the pod to terminate and disappear.

Example taskworkload:
```
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: TaskWorkload
metadata:
  name: taskworkload-sample
spec:
  image: alpine
  command:
    - sleep
    - "100"
```
