### ISSUE TITLE
[Feature]: `kubectl` user can run a `TaskWorkload` using an image stored in a private registry

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1463]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**GIVEN** I am hosting my container image on a private registry
**AND** I have created a `Secret` of type `kubernetes.io/dockerconfigjson` (e.g. by using [`kubectl create secret docker-registry`](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line))
**WHEN I** [run a `TaskWorkload`](https://github.com/cloudfoundry/korifi/issues/1397) looking like this:
```yaml
---
apiVersion: workloads.cloudfoundry.org/v1alpha1
kind: TaskWorkload
metadata:
  name: my-task
  namespace: my-namespace
spec:
  image: <my-private-container-image>
  command: ["echo", "hello"]
  imagePullSecrets:
  - name: <my-secret-name>
```
**THEN I** see the corresponding `Pod`'s `imagePullSecrets` is the same to the one I specified
**AND** the `Pod` is able to pull the image
