### ISSUE TITLE
[Feature]: `TaskWorkload` pods should be secure enough to run in namespaces created by Korifi

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1490]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**WHEN I** create a CF space
**WHEN I** [run a `TaskWorkload`](https://github.com/cloudfoundry/korifi/issues/1397) looking like this:
```yaml
---
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: TaskWorkload
metadata:
  name: my-task
  namespace: <cf-space-name>
spec:
  image: <a-public-container-image>
  command: ["echo", "hello"]
  resources:
    limits:
      cpu: 1000
      memory: 1024
      ephemeral-storage: 1024
    requests:
      cpu: 500
      memory: 512
      ephemeral-storage: 512
```
**THEN I** see the corresponding `Pod` starts successfully

### Dev Notes

As of today the pod would not start as it violates the `restricted` security context of the CF space namespace.
