### ISSUE TITLE
[Feature]: `TaskWorkload` pods should not have access to service account credentials

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#1492]
### Background

**As a** job-task-runner user
**I want** my tasks not to be able to elevate permissions
**So that** task code can only run with minimal privileges

### Acceptance Criteria

**GIVEN** A workload task reconciled by the job-task-runner
**AND** command is `sleep 1000`, say
**WHEN I** shell into the running container
**THEN I** do not see any credentials mounted at `/var/run/secrets/kubernetes.io/serviceaccount`

**Comment by kieron-dev** [comment]
Handy task workload yaml that has a public non-run-as-root image:
```
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: TaskWorkload
metadata:
  name: my-task
spec:
  image: europe-west1-docker.pkg.dev/cf-on-k8s-wg/install-test/droplets/069235b6-9bad-4a5c-8557-7c3e08c83348
  command: ["sleep", "1200"]
```
