### ISSUE TITLE
[Bug]: BuildWorkload.spec.buildRef should be set

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1536]
### What happened?

Here's an example `BuildWorkload` created by korifi today via `cf push`:

```yaml
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: BuildWorkload
metadata:
  name: a43c12b2-c74f-4148-b05e-6c979967e09a
  namespace: cf-space-33605430-913c-4813-954c-f1663766cf21
spec:
  buildRef: {}
  env:
    - name: VCAP_SERVICES
      valueFrom:
        secretKeyRef:
          key: VCAP_SERVICES
          name: bac3f5af-b770-4c81-ad51-8d331a76b7e4-vcap-services
  reconcilerName: kpack-image-builder
  source:
    registry:
      image: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages/6643fd63-3929-4a38-8c65-89fc06efe0c2@sha256:987d6b085314a16ba5566fd0821d5a2f59e1a54ea11b8c0e2cd09309482d0481
      imagePullSecrets:
        - name: image-registry-credentials
```

Notice that `spec.buildRef` is empty when it should not be.

### What you expected to happen

The `spec.buildRef` field should look like this instead:

```yaml
spec:
  buildRef:
    name: a43c12b2-c74f-4148-b05e-6c979967e09a
```

`spec.buildRef.name` should be the name of the `CFBuild` that triggered the creation of the `BuildWorkload`

### Acceptance Criteria

GIVEN a korifi deployment
WHEN I cf push an app
THEN I should see that the `BuildWorkload` that was created has a `spec.buildRef.name` equal to the `metadata.name` of the `CFBuild` created by the `cf push`

---

WHEN I save the `BuildWorkload`'s yaml to my disk
AND I edit it to remove `spec.buildRef.name`
AND I delete the `BuildWorkload` via kubectl
AND I apply the edited `BuildWorkload` to the cluster
THEN I should see that the command fails due to a missing required field `spec.buildRef.name`.

### How to reproduce it (as minimally and precisely as possible)

See above

### Anything else we need to know?

This probably happened because we used the kubernetes LocalObjectRef struct, which makes the name optional. We either need to find an existing struct where it is required or write our own struct where the field is required.

### Environment

Revision of codebase: 0614c147da15ed8cb0c9f8f83f170b0dbc193f0b
Kubernetes version (use `kubectl version`): 1.23
Cloud provider or hardware configuration: kind
Others:
