### ISSUE TITLE
[Feature]: Operator can install the Korifi API with our new Helm distribution

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1572]
### Background

**As an** operator
**I want** to install Korifi easily
**So that** I can give it a try

### Acceptance Criteria

**GIVEN** I have a kind cluster
**AND** I have built and side-loaded the `api` image
**AND** my `dist/api/values.yaml` looks like this:
```yaml
image: <the-api-image>
rootNamespace: cf
externalFQDN: localhost
internalPort: 9000
lifecycle:
  type: buildpack
  stack: cflinuxfs3
  stagingRequirements:
    memoryMB: 1024
    diskMB: 1024
packageRegistry:
  base: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages
  secret: image-registry-credentials
defaultDomainName: vcap.me
```
**WHEN I** run the following commands from my Korifi working copy:
```sh
helm install dist/api
```
**THEN I** see that `api` is installed correctly, including `spec.virtualhost.fqdn` in the `projectcontour.io/v1/HTTPProxy` called `korifi-api-proxy` being `localhost`

### Dev Notes

* See the [proposal](https://docs.google.com/document/d/17FlAVM-t0g9vrNN6e73KYQX5hIwhFpAbbF3s7rPbAow/edit?usp=sharing) for more details.
* We still don't want to implement a centralised chart - we're happy with users installing components separately.
* All values above except:

  - `externalFQDN`
  - `packageRegistry.base`
  - `defaultDomainName`
  
  should be defaulted with the values specified in the example.
