### ISSUE TITLE
[Feature]: Operator can install the Korifi controllers with our new Helm distribution

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1577]
### Background

**As an** operator
**I want** to install Korifi easily
**So that** I can give it a try

### Acceptance Criteria

**GIVEN** I have a kind cluster
**AND** I have built and side-loaded the `controllers` image
**AND** my `dist/controllers/values.yaml` looks like this:
```yaml
image: <the-controllers-image>
rootNamespace: cf
reconcilers:
  build: kpack-image-builder
  app: statefulset-runner
processDefaults:
  memoryMB: 1024
  diskQuotaMB: 1024
packageRegistry:
  secret: image-registry-credentials
taskTTL: 5s
workloadsTLSSecret:
  name: korifi-workloads-ingress-cert
  namespace: korifi-controllers-system
```
**WHEN I** run the following commands from my Korifi working copy:
```sh
helm install dist/controllers
```
**THEN I** see that `controllers` is installed correctly

### Dev Notes

* See #1572.
* All values above should be defaulted with the values specified in the example.
