### ISSUE TITLE
[Feature]: Operator can install the `kpack-image-builder` with our new Helm distribution

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1578]
### Background

**As an** operator
**I want** to install Korifi easily
**So that** I can give it a try

### Acceptance Criteria

**GIVEN** I have a kind cluster
**AND** I have built and side-loaded the `kpack-image-builder` image
* **AND** my `dist/kpack-image-builder/values.yaml` looks like this:
  ```yaml
  image: <the-kpack-image-builder-image>
  rootNamespace: cf
  kpackImageTag: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images
  ```
  **WHEN I** run the following commands from my Korifi working copy:
  ```sh
  helm install dist/kpack-image-builder
  ```
  **THEN I** see that `kpack-image-builder` is installed correctly
  **AND** a default `ClusterStore`, `ClusterStack` and `ClusterBuilder` have been created
* **AND** my `dist/kpack-image-builder/values.yaml` looks like this:
  ```yaml
  rootNamespace: cf
  clusterBuilderName: my-cluster-builder
  kpackImageTag: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images
  ```
  **WHEN I** run the following commands from my Korifi working copy:
  ```sh
  helm install dist/kpack-image-builder
  ```
  **THEN I** see that `kpack-image-builder` is installed correctly
  **AND** no `ClusterStore`, `ClusterStack` or `ClusterBuilder` were created

### Dev Notes

* See #1572.
* All values above except `kpackImageTag` should be defaulted with the values specified in the example.
