### ISSUE TITLE
[Feature]: Developer can push apps using the top-level `command` field in the manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1583]
### Background

**As a** developer
**I want** top-level process configuration in manifests to be supported
**So that** I can use shortcut `cf push` flags like `-c`, `-i`, `-m` etc.

### Acceptance Criteria

* **GIVEN** I have the sources of an application (e.g. `tests/smoke/assets/test-node-app`)
  **AND** `manifest.yml` looks like this:
  ```yaml
  ---
  applications:
  - name: my-app
    command: sleep 123
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with an output similar to this:
  ```
  name:              test
  requested state:   started
  routes:            test.vcap.me
  last uploaded:     Mon 29 Aug 16:28:36 UTC 2022
  stack:             cflinuxfs3
  buildpacks:
          name               version   detect output   buildpack name
          nodejs_buildpack   1.7.61    nodejs          nodejs

  type:            web
  sidecars:
  instances:       1/1
  memory usage:    256M
  start command:   sleep 123
       state     since                  cpu    memory          disk           details
  #0   running   2022-08-29T16:28:54Z   1.6%   42.3M of 256M   115.7M of 1G
  ```
* **GIVEN** I have the same app with the following manifest:
  ```yaml
  ---
  applications:
  - name: my-app
    command: sleep 456
    processes:
      type: web
      command: sleep 123
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with the same output as above
