### ISSUE TITLE
[Feature]: Developer can push apps using the top-level `disk_quota` field in the manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1584]
### Background

**As a** developer
**I want** top-level process configuration in manifests to be supported
**So that** I can use shortcut `cf push` flags like `-c`, `-i`, `-m` etc.

### Acceptance Criteria

* **GIVEN** I have the sources of an application (e.g. `tests/smoke/assets/test-node-app`)
  **AND** `manifest.yml` looks like this:
  ```yaml
  ---
  applications:
  - name: my-app
    disk_quota: 2G
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with an output similar to this:
  ```
  name:              test
  requested state:   started
  routes:            test.vcap.me
  last uploaded:     Mon 29 Aug 16:28:36 UTC 2022
  stack:             cflinuxfs3
  buildpacks:
          name               version   detect output   buildpack name
          nodejs_buildpack   1.7.61    nodejs          nodejs

  type:            web
  sidecars:
  instances:       1/1
  memory usage:    256M
  start command:   npm start
       state     since                  cpu    memory          disk           details
  #0   running   2022-08-29T16:28:54Z   1.6%   42.3M of 256M   115.7M of 2G
  ```
* **GIVEN** I have the same app with the following manifest:
  ```yaml
  ---
  applications:
  - name: my-app
    disk_quota: 3G
    processes:
    - type: web
      disk_quota: 2G
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with the same output as above

**Comment by kieron-dev** [comment]
It seems the app level field in the manifest is `disk-quota` with a hyphen. Yet it is `disk_quota` with an underscore at process level.

If we provide `disk_quota` at the application level in a manifest, the CLI discards it. See https://github.com/cloudfoundry/cli/commit/bb1245bf5d1

**Comment by kieron-dev** [comment]
If you pass a manifest via the CLI like
```
applications:
  - name: node
    memory: 123M
    disk-quota: 256M
    processes:
      - type: web
        memory: 124M
        disk-quota: 512M
```

It will forward that to the API as:
```
applications:
  - name: node
    memory: 123M
    disk-quota: 256M
    processes:
      - type: web
        memory: 124M
        disk_quota: 512M
```

Note that it has changed the process level field name _only_.

I guess our API should support `disk_quota` at the process level, as per the docs, and `disk-quota` at the app level, as per the behaviour.

What do you think @gcapizzi ?
