### ISSUE TITLE
[Feature]: Developer can push apps using the top-level `health-check-http-endpoint` field in the manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1589]
### Background

**As a** developer
**I want** top-level process configuration in manifests to be supported
**So that** I can use shortcut `cf push` flags like `-c`, `-i`, `-m` etc.

### Acceptance Criteria

* **GIVEN** I have the following node app:
  ```js
  var http = require('http');
  http.createServer(function (request, response) {
    if (request.url == '/health') {
      response.writeHead(200, {'Content-Type': 'text/plain'});
      response.end('ok');
    } else {
      response.writeHead(500, {'Content-Type': 'text/plain'});
      response.end('no');
    }
  }).listen(process.env.PORT);
  ```
  with the following `manifest.yml`:
  ```yaml
  ---
  applications:
  - name: real-app
    health-check-http-endpoint: /health
    processes:
    - type: web
      health-check-type: http
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with an output similar to this:
  ```
  name:              test
  requested state:   started
  routes:            test.vcap.me
  last uploaded:     Mon 29 Aug 16:28:36 UTC 2022
  stack:             cflinuxfs3
  buildpacks:
          name               version   detect output   buildpack name
          nodejs_buildpack   1.7.61    nodejs          nodejs

  type:            web
  sidecars:
  instances:       1/1
  memory usage:    256M
  start command:   npm start
       state     since                  cpu    memory          disk           details
  #0   running   2022-08-29T16:28:54Z   1.6%   42.3M of 256M   115.7M of 1G
  ```
* **GIVEN** I have the same app with the following manifest:
  ```yaml
  ---
  applications:
  - name: my-app
    health-check-http-endpoint: /wrong
    processes:
    - type: web
      health-check-type: http
      health-check-http-endpoint: /health
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with the same output as above
