### ISSUE TITLE
[Feature]: Developer can push apps using the top-level `health-check-type` field in the manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1590]
### Background

**As a** developer
**I want** top-level process configuration in manifests to be supported
**So that** I can use shortcut `cf push` flags like `-c`, `-i`, `-m` etc.

### Acceptance Criteria

* **GIVEN** I have the following node app:
  ```js
  var http = require('http');
  http.createServer(function (request, response) {
    response.writeHead(500, {'Content-Type': 'text/plain'});
    response.end('no');
  }).listen(process.env.PORT);
  ```
  with the following `manifest.yml`:
  ```yaml
  ---
  applications:
  - name: real-app
    health-check-type: http
  ```
  **WHEN I** `cf push`
  **THEN I** see the push fails
* **GIVEN** I have the same app with the following manifest:
  ```yaml
  ---
  applications:
  - name: my-app
    health-check-type: port
    processes:
    - type: web
      health-check-type: http
  ```
  **WHEN I** `cf push`
  **THEN I** see the push fails
