### ISSUE TITLE
[Feature]: Developer can push apps using the top-level `timeout` field in the manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1598]
### Background

**As a** developer
**I want** top-level process configuration in manifests to be supported
**So that** I can use shortcut `cf push` flags like `-c`, `-i`, `-m` etc.

### Acceptance Criteria

* **GIVEN** I have the following node app:
  ```js
  var http = require('http');

  const DOWNTIME_SECONDS = 65;
  var downUntil = new Date().getTime() + DOWNTIME_SECONDS * 1000;

  http.createServer(function (request, response) {
      var now = new Date().getTime();

      if (now > downUntil) {
          response.writeHead(200, {'Content-Type': 'text/plain'});
          response.end('ok');
      } else {
          response.writeHead(500, {'Content-Type': 'text/plain'});
          response.end('no - wait for ' + (downUntil - now) / 1000 + ' seconds');
      }
  }).listen(process.env.PORT);
  ```
  with the following `manifest.yml`:
  ```yaml
  ---
  applications:
  - name: real-app
    timeout: 70
    processes:
    - type: web
      health-check-type: http
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with an output similar to this:
  ```
  name:              test
  requested state:   started
  routes:            test.vcap.me
  last uploaded:     Mon 29 Aug 16:28:36 UTC 2022
  stack:             cflinuxfs3
  buildpacks:
          name               version   detect output   buildpack name
          nodejs_buildpack   1.7.61    nodejs          nodejs

  type:            web
  sidecars:
  instances:       1/1
  memory usage:    256M
  start command:   npm start
       state     since                  cpu    memory          disk           details
  #0   running   2022-08-29T16:28:54Z   1.6%   42.3M of 256M   115.7M of 1G
  ```
* **GIVEN** I have the same app with the following manifest:
  ```yaml
  ---
  applications:
  - name: my-app
    timeout: 50
    processes:
    - type: web
      health-check-type: http
      timeout: 70
  ```
  **WHEN I** `cf push`
  **THEN I** see the push succeeds with the same output as above

### Dev Notes

* The default `timeout` is 60 seconds - if we're not applying this default properly already, we should.
