### ISSUE TITLE
[Feature]: Operator can install a full Korifi with our new Helm distribution

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1704]
### Blockers/Dependencies

* #1572 
* #1577 
* #1578 
* #1579 
* #1580 

### Background

**As an** operator
**I want** to install Korifi easily
**So that** I can give it a try

### Acceptance Criteria

**GIVEN** I have a kind cluster
**AND** I have built and side-loaded all Korifi images
**AND** my `dist/main/values.yaml` looks like this:
```yaml
api:
  externalFQDN: localhost
  packageRegistryBase: localregistry-docker-registry.default.svc.cluster.local:30050/kpack/packages
  defaultDomainName: vcap.me
kpack-image-builder:
  kpackImageTag: localregistry-docker-registry.default.svc.cluster.local:30050/korifi-controllers/kpack/images
```
**WHEN I** run the following commands from my Korifi working copy:
```sh
helm install dist/main
```
**THEN I** get a working Korifi installation

### Dev Notes

* We want to promote shared fields, like `rootNamespace` and `packageRegistrySecret`, to [Helm globals](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#global-chart-values). This makes it harder to install the individual charts as standalone, but it's not really a use case we care about.
* A cleanup of the values we expose might be in order - but we can do it later.
