### ISSUE TITLE
[Bug]: CFDomain doesn't permit domain names that start with a number

### ISSUE THREAD

**Issue by adamfowleruk** [cloudfoundry/korifi#1708]
### What happened?

Coniguring default domain as per CFDomain here: https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md#default-cf-domain

Resulted in this error message:-
```
The CFDomain "default-domain" is invalid: spec.name: Invalid value: "apps.aws.12factor.xyz": spec.name in body should match '^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$'
```

Testing this regex online shows that having '12' at the beginning of a domain is not accepted.

### What you expected to happen

Expected this to work as all other config with this domain name was accepted except CFDomain config.

### Acceptance Criteria

GIVEN a base domain of apps.aws.12factor.xyz
WHEN I apply the CFDomain config as per the above INSTALL.md file
THEN I see this domain is accepted

### How to reproduce it (as minimally and precisely as possible)

```sh
export ROOT_NAMESPACE="cf"
export ADMIN_USERNAME="cf-admin"
export BASE_DOMAIN="aws.12factor.xyz"

cat <<EOF | kubectl apply --namespace "$ROOT_NAMESPACE" -f - 
apiVersion: korifi.cloudfoundry.org/v1alpha1
kind: CFDomain
metadata:
  name: default-domain
  namespace: $ROOT_NAMESPACE
spec:
  name: "apps.$BASE_DOMAIN"
EOF
```

### Environment

Revision of codebase: 0.2.0 release tgz
Kubernetes version (use `kubectl version`): 
 - Client Version: v1.25.2
 - Kustomize Version: v4.5.7
 - Server Version: v1.22.13-eks-15b7512
Cloud provider or hardware configuration: EKS
Others:

**Comment by adamfowleruk** [comment]
Adding 0-9 here fixed the issue:-

WAS:-
```yaml
            description: CFDomainSpec defines the desired state of CFDomain
            properties:
              name:
                description: Domain name is required and must conform to RFC 1035
                pattern: ^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$
                type: string
```

WORKS:-
```yaml
            description: CFDomainSpec defines the desired state of CFDomain
            properties:
              name:
                description: Domain name is required and must conform to RFC 1035
                pattern: ^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$
                type: string
```
(Note the additional 0-9 after the \. part.

**Comment by danail-branekov** [comment]
@adamfowleruk Thanks for reporting the issue. As you already found a solution, would you be interested in PR-ing it?

**Comment by adamfowleruk** [comment]
@danail-branekov Will do, but mid Hackathon with a customer this week!

**Comment by tcdowney** [comment]
I'm not sure why we made this strictly conform to the RFC 1035 DNS label restrictions. Contour and most Kubernetes resources support the RFC 1123 amendments which allow a leading numeric character.

https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names

Also here's the regex that Cloud Controller uses.
https://github.com/cloudfoundry/cloud_controller_ng/blob/4a23a419862ef9b7272f411a4435e33fc7305f30/lib/cloud_controller/domain_decorator.rb#L3

I'm not sure it's good to just use that wholesale since what Gorouter supports might be subtly different from what most K8s ingress controllers support, but it's good to have for reference.

**Comment by adamfowleruk** [comment]
Even worse, when eventually getting past this and then trying to do a cf push (and thus creating a route) I get a wonderful new error:-

```sh
cf push firstflask
Pushing app firstflask to org MyNewOrg / space FirstSpace as arn:aws:iam::656667300755:user/cf-admin...
FQDN 'firstflask.apps.aws.12factor.xyz' does not comply with RFC 1035 standards
FAILED
```

Hunting down the only mention of RFC 1035 and checking the regex shows that this IS valid. As per the CFDomain entry:-

```yaml
spec:
            description: CFDomainSpec defines the desired state of CFDomain
            properties:
              name:
                description: The domain name. It is required and must conform to RFC
                  1035
                pattern: ^[a-zA-Z]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$
                type: string
            required:
            - name
            type: object
```

But its still failing, so I think your CloudController entry above is my issue - which I cannot fix outside of the code...
