### ISSUE TITLE
[Feature]: App Developer can set labels/annotations on Apps via the app manifest

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1945]
### Background

**As an** App Developer
**I want** to be able to set labels and annotations on Apps via the [application manifest](https://v3-apidocs.cloudfoundry.org/version/3.128.0/index.html#manifests)
**So that** provide my own labels and annotations to the `CFApp` resource

See the epic issue for additional context on this feature:
https://github.com/cloudfoundry/korifi/issues/1357

### Acceptance Criteria

There are various limitations in place for label/annotation keys and values that we need to validate against. These are described by the Cloud Controller API docs below (but are also the same as their Kubernetes counterparts).

Annotation keys and values: https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#labels-and-selectors
Label keys and values: https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#labels-and-selectors

In general these APIs should abide by the same design and validations as the Cloud Controller ones:
https://v3-apidocs.cloudfoundry.org/version/3.101.0/index.html#updating-labels-and-annotations

---

#### Setting New Labels/Annotations

**WHEN I** push an app with the following manifest:
```yaml
---
applications:
- name: APP-NAME
  metadata:
    labels:
      foo: FOO
    annotations:
      bar: BAR
```
**THEN I** see the those labels and annotations reported back with the object in the response and I can see them set on the `metadata.labels` and `metadata.annotations` sections of the corresponding `CFApp` resource.

---

#### Updating Existing Labels/Annotations

**GIVEN** I have pushed an app with the following manifest:
```yaml
---
applications:
- name: APP-NAME
  metadata:
    labels:
      foo: FOO
    annotations:
      bar: BAR
```
**WHEN I** push the app again with the following manifest:
```yaml
---
applications:
- name: APP-NAME
  metadata:
    labels:
      foo: FOO2
    annotations:
      bar: BAR2
```
**THEN I** see the existing labels and annotations have been updated both from the returned JSON resource and the `CFApp` resource

---

#### Deleting Existing Labels/Annotations
Labels/annotations are removed by specifying `null` (not the string `"null"`) as the value in the request.

**GIVEN** I have pushed an app with the following manifest:
```yaml
---
applications:
- name: APP-NAME
  metadata:
    labels:
      foo: FOO
    annotations:
      bar: BAR
```
**WHEN I** push the app again with the following manifest:
```yaml
---
applications:
- name: APP-NAME
  metadata:
    labels:
      foo:
    annotations:
      bar:
```
**THEN I** see the existing labels and annotations have been removed both from the returned JSON resource and the `CFApp` resource
