### ISSUE TITLE
[Explore]: Use UAA as identity provider

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2243]
### Background

In order to provide seamless migration from classic CF for VMs to Korifi, users would most probably like to use their existing identity provider so that they do not have to create users from scratch. In the CF for VMs world the identity provider is usually an UAA instance. UAA supports the OpenID Connect (OIDC) protocol which we can leverage to integrate UAA into Korifi clusters.

### Acceptance Criteria

Write a proposal that answers the following questions:
- What do we need to serve in the `/` endpoint. What is the difference between `login` and `uaa` urls. What do we do with the `CFOnK8s` value?
- What else needs to change in korifi?
- How do we configure the cluster with the uaa as an identity provider.
- Does the shim need to know about the uaa (there have been discussions that the cloud controller talks to it in some cases)?
- Do we need to change something in the cf cli around the `CFOnK8s` property?
- Do we need to implement the user management endpoints of the cf api? What would be a viable implementation? (potentially splittable to its own explore)

### Timebox

No timebox

### Dev Notes
We (@georgethebeatle and @danail-branekov) have carried out an internal SAP spike and it looks that doing that is totally feasible. Here is a short list of changes we had to implement:

* Do not return [CFOnK8s](`https://github.com/cloudfoundry/korifi/blob/1ac1277d2cafc57ed1bc1c53f057e25d61815eed/api/presenter/root.go#L37) in the root response (or return `false`, whatever makes more sense)
* Advertise the `uaa` and `login` URLs in the root response. In our spike the two values are pointing to the UAA. Maybe we should test with a custom login screen.
* The two points above makes the CLI talk to the UAA directly, i.e. the CLI would get the user token from UAA which is validated by the cluster OIDC provider (see below)
* Configure the k8s cluster to use OIDC, e.g. put the following sample args to the kube-api server:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /ssl
    hostPath: #/path/to/router_ssl.certificate
    readOnly: true
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraVolumes:
        - name: ssl-certs
          hostPath: /ssl
          mountPath: /etc/uaa-ssl
      extraArgs:
        oidc-issuer-url: https://uaa.mel-c.korifi.cf-app.com/oauth/token
        oidc-client-id: cloud_controller
        oidc-ca-file: /etc/uaa-ssl/ca.pem
        oidc-username-claim: user_name
        oidc-username-prefix: "uaa:"
        oidc-signing-algs: "RS256"
```

  - the value of `nodes/extraMounts/hostPath` should reference a file where the UAA certificate is stored. For the `mel-c` environment, the certificate can be obtained from the `router_ssl.certificate` cf-var, i.e. `yq e ".router_ssl.certificate" <"$HOME/workspace/cf-k8s-secrets/bosh-lite-cf/directors/mel-c/deployments/cf-vars.yml"`
  - The `oidc-client-id` has to be one of the JWT token audiences. We have chosen to use `cloud_controller` but we are not sure whether it is the right one.
  - The `oidc-username-prefix` should be configured to the JWT token origin, in the `mel-c` deployment this is `uaa` but can vary (we have seen that in SAP deployments)
  - The `oidc-username-claim` has to be one of the claims in the token, it seems that `user_name` and `email` are common, it should be up to the operator to pick the preferred one.

* The `create role` api method has to take the user origin from the request and use it as an OIDC prefix when creating the role binding. Here is a simple diff where we have implemented that:

```
diff --git a/api/payloads/role.go b/api/payloads/role.go
index 61c6912c..4a03745f 100644
--- a/api/payloads/role.go
+++ b/api/payloads/role.go
@@ -21,6 +21,7 @@ type (
        UserRelationshipData struct {
                Username string `json:"username" validate:"required_without=GUID"`
                GUID     string `json:"guid" validate:"required_without=Username"`
+               Origin   string `json:"origin"`
        }

        RoleRelationships struct {
@@ -55,6 +56,15 @@ func (p RoleCreate) ToMessage() repositories.CreateRoleMessage {
        if p.Relationships.User != nil {
                record.Kind = rbacv1.UserKind
                record.User = p.Relationships.User.Data.Username
+
+               // For UAA Authenticated users, prefix the Origin as our Cluster uses the Orgin:User for
+               // Authentication verification (via OIDC prefixs)
+               // --kube-apiserver-arg oidc-username-prefix="<origin>:"
+               // --kube-apiserver-arg oidc-groups-prefix="<origin>:"
+               if p.Relationships.User.Data.Origin != "" {
+                       record.User = p.Relationships.User.Data.Origin + ":" + record.User
+               }
+
                if p.Relationships.User.Data.GUID != "" {
                        record.User = p.Relationships.User.Data.GUID
                }
```

_No response_
