### ISSUE TITLE
[Feature]: Korifi api users should be able to use long API/workloads URLs

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2425]
### Background

The helm chart of Korifi creates ingress certificates for the [api](https://github.com/cloudfoundry/korifi/blob/51933b124053fc3fff1bc4ba208ac701f9311b21/helm/korifi/api/ingress-cert.yaml#L8) and [workload](https://github.com/cloudfoundry/korifi/blob/51933b124053fc3fff1bc4ba208ac701f9311b21/helm/korifi/controllers/ingress-cert.yaml#L8). In doing so it sets both the CN and the subject alternative names (spec.dnsNames) to the value of `.Values.global.defaultAppDomainName`. This works well in most cases, but the CN field has a size limit of 64 characters, meaning that users have an upper limit for the total length of their api url. Removing the CN from the certificates is not an option because [various runtimes](https://github.com/cert-manager/cert-manager/issues/3634) still require it.

### Action to take

We should give users a way to set the CN to a custom value, while keeping the subject alternative namess unchanged

**GIVEN** I deploy korifi with the following values:
```yaml
global:
  defaultAppDomainName: "apps.toooooooooooooooooooooooooooo-loooooooooooooooooooooong-url.127-0-0-1.nip.io"
  commonName: "*.127-0-0-1.nip.io"

api:
  apiServer:
    url: "api.toooooooooooooooooooooooooooo-loooooooooooooooooooooong-url.127-0-0-1.nip.io"
```
**THEN** deployment is successful
**AND** I can push an app and request its route
