### ISSUE TITLE
Document breaking changes for 0.11.0

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#3057]
* the new required `networking.GatewayClass` helm value is introduces
* `api.expose` helm value is removed (deployment will succeed but behaviour will be different)
* `contourRouter.include` is removed (deployment will succeed but behaviour will be different)
* Short downtime due to Contour restart. Downtime mitigation ideas
  * Enable Contour dynamic provisioning
  * Manually create a new TLSCertificateDelegation object before upgrading in order to keep existing HTTPProxies work:

```
apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: korifi-controllers-workloads-fallback-delegation
  namespace: {{ .Release.Namespace }}
spec:
  delegations:
  - secretName: korifi-workloads-ingress-cert
    targetNamespaces:
    - '*'
```
