### ISSUE TITLE
Support `--var` in `cf push`

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#3384]
Acceptance

## Acceptance
**GIVEN** I have pushed an app via `cf push --var FOO=var`, e.g.
`cf push dorifi --var FOO=bar -p ~/workspace/korifi/tests/assets/dorifi`

**WHEN** The app has started

**THEN** I can see the `FOO` env var set to `bar` in the application environment, e.g.
`curl -k https://dorifi.apps-127-0-0-1.nip.io/env.json | jq .FOO` should return `bar`

## Dev notes
That environment variable should be made available into the `<app-guid>-env` secret. 

FWIW, pushing the app via a manifest with `env`, e.g. 

```
---
applications:
- name: dorifi
  path: /home/ccloud/workspace/korifi/tests/assets/dorifi
  env:
    FOO: bar
```
works as expected, i.e. the env secret contains a `FOO` entry and the application gets the `FOO` env var
