### ISSUE TITLE
Support floating point number values for disk_quota in application manifest

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#3546]
### Backgroundo

It turns out it is possible to push a manifest like this one on CF for VMs

```
---
applications:
- name: test-sapmachine
  memory: 800M
  path: ./target/application.war
  instances: 1
  disk_quota: 1.5G
```

As of today Korifi assumes `disk_quota` to be an integer

### Acceptance

**GIVEN** I have targeted a space on a Korifi deployment
**WHEN** I push a manifest with a decimal amount of `disk_quota`
**THEN** the application starts
