### ISSUE TITLE
[Feature]: Operator can create a CFSpace Custom Resource

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#764]
### Blockers/Dependencies

#763 

### Background

**As a** k8s operator
**I want** to create CFSpaces in my org namespace
**So that** I can make spaces declaratively

The gist of this story is that we will create a new CFSpace CRD and corresponding controller, and copy the current logic for space creation from the API shim down into the reconcile loop for the controller.

The controller will wait for the HNC subnamespace anchor to be "ready" before reporting readiness.

### Acceptance Criteria

**GIVEN** I have cluster admin
**WHEN I** list CRDs 
**THEN I** see that there is a CFSpace CRD

**GIVEN** I have cf-admin role in my org namespace
**WHEN I** kubectl apply a CFSpace object in my org namespace as follows:
```
apiVersion: workloads.cloudfoundry.org/v1alpha1
kind: CFSpace
metadata:
  name: <space-guid>
  namespace: <org-guid>
spec:
  name: <space-name>
```
**THEN I** see that eventually the status is updated to reflect the name guid of the space as follows:
```
status:
  guid: <space-guid>
```
**AND I** see that a corresponding SubnamespaceAnchor has been created in the org namespace, with its name matching the space guid, and `metadata/labels` has a label for the space name as follows:
```
metadata:
  ...
  labels:
    cloudfoundry.org/space-name: <space-name>
```
**AND I** see that the new SubnamespaceAnchor has an owner reference to the CFSpace object
**AND**
**WHEN I** list spaces from the CLI using `cf -o org spaces`
**THEN I** see the space is listed. 

### Dev Notes

**Note** that there is currently logic in the API shim to wait after a subnamespace is "ready", until it sees that HNC has given the current user rights to the new namespace. That code probably will need to remain in the API shim, since the controller reconcile loop doesn't know who the "current user" is, and we don't have a better method for determining namespace readiness.
