### ISSUE TITLE
[Feature]: Service binding credentials in `VCAP_SERVICES` can be stored in a single `Secret`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#796]
### Background

Service Bindings contain often include secret credentials (e.g. database passwords, api tokens, etc.) so the current approach of aggregating them all in plaintext under the `VCAP_SERVICES` env var on the `StatefulSet` (and kpack `Image` after #774) isn't the best.

#### Example Current StatefulSet
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
  name: 718c9a94-13b5-4af5-93b7-37ce133a1400-4e7122cf5c
  namespace: e9d1f8dc-c9fe-4565-8aa1-75775c07b050
  ...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - command:
        ...
        env:
        ...
        - name: VCAP_SERVICES
          value: '{"user-provided":[{"label":"user-provided","name":"service-a","tags":[],"instance_guid":"121483d9-1867-4b25-8ab0-08870ed9a658","instance_name":"service-a","binding_guid":"3155f595-148b-4d04-8892-e320aff5cfe9","binding_name":null,"credentials":{"service-a-cred":"something-secret-from-service-a","type":"user-provided","url":"jdbc:sqlserver://mysql.example.com/my-db:3306"},"syslog_drain_url":null,"volume_mounts":[]}]}'
        - name: PORT
          value: "8080"
        - name: VCAP_APP_HOST
          value: 0.0.0.0
        ...
```

Alternatively we could build up `VCAP_SERVICES` in a Kubernetes `Secret`. `Secrets` are more likely to have special care taken with them when it comes to access and logging and are more and more often [encrypted at rest in etcd](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/).

So if we could update our design to aggregate and store binding credentials for an app in a single secret then we could improve things by [referencing that secret directly in the env var config](https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables). This might look something like this:

#### Example Future StatefulSet
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  ...
  name: 718c9a94-13b5-4af5-93b7-37ce133a1400-4e7122cf5c
  namespace: e9d1f8dc-c9fe-4565-8aa1-75775c07b050
  ...
spec:
  ...
  template:
    ...
    spec:
      ...
      containers:
      - command:
        ...
        env:
        ...
        - name: VCAP_SERVICES
          valueFrom:
          secretKeyRef:
            name: <app-guid>-vcap-services-secret
            key: vcap_services
        - name: PORT
          value: "8080"
        - name: VCAP_APP_HOST
          value: 0.0.0.0
        ...
```

---

### What would need to be done

1. We would need to update some controller (probably the `CFServiceBinding` controller) to manage and update a "vcap-services" `Secret` for the app since this secret needs to contain aggregated credentials from every binding. It would do something similar to what the [Process controller](https://github.com/cloudfoundry/cf-k8s-controllers/blob/04eedfd6695374d0e92f129a3f5f82235ccd5f7c/controllers/controllers/workloads/cfprocess_controller.go#L427) is doing today.
2. Update the Eirini LRP and [eirini-controller](https://github.com/cloudfoundry/eirini-controller) to support a [K8s EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvar-v1-core) type [instead of the string map it uses today for environment variables](https://github.com/cloudfoundry/eirini-controller/blob/95c7b7ce3abec9f24381e71c3034c0573609b95c/pkg/apis/eirini/v1/lrp.go#L41)
3. Update the Process Controller to just pass through the `Secret` we've made when constructing the Eirini LRP
4. Assuming #774 is done we'll need to update how we create kpack `Image` resources to reference the `Secret`

---

**As an** App Developer
**I want** my service binding credentials to be referenced using `Secrets`
**So that** they don't appear in plaintext when I view my workload resources

### Acceptance Criteria

**GIVEN** I have pushed an app and bound a user-provided service instance to it
**WHEN I** inspect the app's `StatefulSet` and `Pod`
**THEN I** do not directly see any of the credentials from the service binding

### Dev Notes

* [Kpack already uses the EnvVar type directly](https://github.com/pivotal/kpack/blob/main/pkg/apis/build/v1alpha2/image_types.go#L67)
  * This is cool cause we can also load EnvVars from `ConfigMaps` and stuff in addition to `Secrets`
* Technically for backwards compatibility we should add a new field to the LRP instead of just replacing `Env`. Could probably just call it `EnvVars` or something 🤷
