### ISSUE TITLE
[Feature]: Eirini users can store Task env vars in k8s secrets

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#918]
### Background

Right now Eirini users who want to create a Task are forced to set any env vars explicitly as string key value pairs, which means the information that is potentially sensitive for the task can be exposed to whoever has permission to read Tasks on the cluster.

This defect is due to today's [Task definition](https://github.com/cloudfoundry/eirini-controller/blob/95c7b7ce3abec9f24381e71c3034c0573609b95c/pkg/apis/eirini/v1/task.go#L30) and should be fixed so that users of Eirini can set env vars with values coming from Secrets, ConfigMaps, etc.

**As a** Eirini user
**I want** to be able to create Tasks with env values from secrets
**So that** I do not expose sensitive information

### Acceptance Criteria

**GIVEN** I have read/write permissions for Tasks in the cluster
**WHEN I** I apply the following yml
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: $(echo -n "s33msi4" | base64 -w0)
---
apiVersion: eirini.cloudfoundry.org/v1
kind: Task
metadata:
  name: mytask
  namespace: cf-workloads
spec:
  GUID: random-guid
  image: eirini/busybox
  command: ["/bin/env"]
  env:
  - foo: bar
  environment:
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysecret
        key: password
        optional: false
```
**THEN I** expect it to be accepted
**AND I** expect my to see both the `foo: bar` and the `password: s33msi4` env vars printed in the Task output

### Dev Notes

In order to keep Eirini's contract backwards compatible we could introduce a new field for env vars of type `[]corev1.EnvVar` next to the current one and deprecate the current one. The implementation would merge the values in the two env var fields thus not breaking old clients, but giving new clients the opportunity to hide their env values in secrets. Eventually after some time we would delete the deprecated field.
